---
title: "finalpro"
output: html_document
date: '2022-12-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(numDeriv)
library(assertthat)

# main function that does initialization, sampling, and updating
main <- function(old_density_function, starting_points=NA, bounds=c(-Inf, Inf), n=20){
  
  # Initialize
  
  
  density_function <- function(x){
    return(log(old_density_function(x)))
  }
  
  starting_points <- get_StartingPoints(starting_points, density_function, bounds)

  
  initialized <- initialize(density_function, starting_points, bounds)
  
  f_deriv <- initialized$f_deriv
  T_values <- initialized$T_values
  calculated_f <- initialized$calculated_f
  calculated_f_deriv <- initialized$calculated_f_deriv
  Z_values <- initialized$Z_values
  U_values <- initialized$U_values
  L_values <- initialized$L_values
  
  
  # Sample and Update
  
  #make empty vector of length n to store the values to return
  return_values <- vector(mode = "numeric", length = n)
  count <- 1

  #sample and update whilst we haven't got enough values
  while(count < n+1){ 
    #sampling step
    
    sampled_step <- sampling_step(T_values, density_function, f_deriv, bounds, Z_values, U_values, calculated_f_deriv, calculated_f) 
    
    x_star <- sampled_step$x_star
    h_eval <- sampled_step$h_eval
    accepted <- sampled_step$accepted
    
      if(accepted == TRUE){
        #if the sample was accepted then add x_star to the return values
        #increase count by 1
        
        return_values[count] <- x_star
        
        count <- count + 1
        
      }
    
    #update step if h(x*) and h'(x*) where evaluated in sampling
    if(h_eval == TRUE){
      
      updated_step <- update_step(x_star, T_values, density_function, f_deriv, bounds, length(T_values))
      
      T_values <- updated_step$T_values
      
      Z_values <- updated_step$Z_values
      U_values <- updated_step$U_values
      L_values <- updated_step$L_values
      calculated_f <- updated_step$calculated_f
      calculated_f_deriv <- updated_step$calculated_f_deriv
      

    } 
  }
  
  assert_that(length(return_values)==n)
  
  return(return_values)
  
}


get_StartingPoints <- function(starting_points, density, bounds){
  # get starting points if non are provided
  # if they are provided, assert that they are on either side of the density maximum
  
  if(is.numeric(starting_points)){
    
    max_value <- optim(starting_points[1], function(x) -1*density(x), method="BFGS")$value
    
    assert_that( ((starting_points[1] < max_value) && (starting_points[2] > max_value)) , msg= 
                   "starting points are not on both sides of max value of function, choose better start points
                  or leave blank" )
    
    return(starting_points)
    
  }
  
  init <- 0
  if(bounds[1] == -Inf){
    if (bounds[2] == Inf){
      init <- 0
    } else {
      init <- bounds[2]-5
    }
  } else {
    if (bounds[2] == Inf){
      init <- bounds[1]+5
    } else {
      boundMean <- (bound[2]-bound[1])/2
      init <- boundMean
    }
  }
  
  max_value <- optim(init, density, method="BFGS")$value
  
  starting_points <- c(max_value-1, max_value+1)
  
  return(starting_points)
  
  
}



init_T <- function(starting_points){
  
  sorted <- sort(starting_points)
  return(sorted)
  
}

find_Z <- function(f_vals, f_deriv_vals, T_values){
  # intersection points
  
  #Check input
  assert_that(is.numeric(f_vals), is.numeric(f_deriv_vals), 
              is.numeric(T_values))
  assert_that( min(c(length(f_vals), length(f_deriv_vals), 
                     length(T_values))) ==
                 max(c(length(f_vals), length(f_deriv_vals), 
                     length(T_values))))
  
  
  n <- length(T_values)-1
  num <- f_vals[2:(n+1)]-f_vals[1:n]-(T_values[2:(n+1)]*f_deriv_vals[2:(n+1)])+
    (T_values[1:n]*f_deriv_vals[1:n])
  den <- f_deriv_vals[1:n]-f_deriv_vals[2:(n+1)]
  
  assert_that(all(den != 0))
  
  Z_values <- num/den
  
  #Check output
  assert_that(is.numeric(Z_values))
  assert_that(length(Z_values) == (length(T_values)-1))
  
  return(Z_values)
  
}

# note that at T_values L and U are just evaluations of f

find_U <- function(x, f_vals, f_deriv_vals, Z_values, T_values, bounds){
  
  #Check input
  assert_that(is.numeric(x), is.numeric(f_vals), is.numeric(f_deriv_vals), 
              is.numeric(Z_values), is.numeric(T_values),
              is.numeric(bounds))
  assert_that( min(c(length(f_vals), length(f_deriv_vals), 
                      length(T_values))) ==
                 max(c(length(f_vals), length(f_deriv_vals), 
                     length(T_values))))
  assert_that(length(x)<=length(T_values))
  assert_that(length(Z_values) == (length(T_values)-1))
  assert_that(length(bounds) == 2, is.numeric(bounds))
  assert_that(bounds[1] < bounds[2])
  
  if(x %in% T_values){
    return(f_vals[match(x,T_values)])
  }
  
  ind <- findInterval(x, c(bounds[1], Z_values, bounds[2]))
  u <- f_vals[ind] + ((x-T_values[ind])*f_deriv_vals[ind])
  
  #Check output
  #assert_that(length(u) == length(T_values))
  assert_that(is.numeric(u))
  
  return(u)
  
}


find_L <- function(x, f_vals, T_values, bounds){
  
  #Check input
  assert_that(is.numeric(x), is.numeric(f_vals),  
              is.numeric(T_values), is.numeric(bounds))
  assert_that( min(c(length(f_vals), length(T_values))) ==
                 max(c(length(f_vals), length(T_values))))
  
  if(x %in% T_values){
    return(f_vals[match(x,T_values)])
  }
  
  ind <- findInterval(x, c(bounds[1], T_values, bounds[2]))

  
  if ( (ind==1) || (ind==(length(T_values)+1)) ){
    return(-Inf)
  }
  
  
  term_1 <- (T_values[ind]-x)*f_vals[ind-1]
  term_2 <- (x-T_values[ind-1])*f_vals[ind]
  term_3 <- (T_values[ind]-T_values[ind-1])
  
  assert_that(term_3 != 0)
  
  L_values <- (term_1+term_2)/term_3
  
  #Check output
  assert_that(is.numeric(L_values))
  #assert_that(length(L_values) == (length(T_values)-1))
  
  return(L_values)
  
}


sample_s <- function(lb, ub, Z_values, U_values, T_values, calculated_f_deriv, calculated_f){
  
  # bounds of integration where lb=lowerbound, Z_values=intersection points, ub=upperbound
  bounds <- c(lb, Z_values, ub)

  # number of starting points
  pt <- length(bounds)-1
  
  
  #vector to store each piecewise cdf
  cdfs <- rep(0, pt)
  
  for(i in seq(1, pt)){
    # integral of U
    
    up <- function(x){ exp(calculated_f[i] + (x-T_values[i])*calculated_f_deriv[i]) }
    cdfs[i] <- integrate(up, bounds[i], bounds[i+1])$value
    
  }
  

  #normalising constant
  normc <- sum(cdfs)
  cdfs <- cdfs/normc

  # choose which cdf interval to sample from 
  cdf_idx <- sample(length(cdfs), prob = cdfs, size=1)
  U <- runif(1)*cdfs[cdf_idx]
  
  if (calculated_f_deriv[cdf_idx] == 0){
    y <- bounds[cdf_idx] + U*(bounds[cdf_idx+1] - bounds[cdf_idx])
  } else {
    num <- (calculated_f_deriv[cdf_idx]*U / exp(calculated_f[cdf_idx])) + exp((bounds[cdf_idx] - T_values[cdf_idx])*calculated_f_deriv[cdf_idx])
    # using taylor expansion of log(x) incase we are taking negative log is negative
    check <- ifelse((num < 0), (num-1) - (1/2)*(num-1)^2 + (1/3)*(num-1)^3, log(num))
    y <- T_values[cdf_idx] + check/calculated_f_deriv[cdf_idx]
  }

  return(y)
  
}



# initialization function that initializes T and calculates U, L, and S at the starting values
initialize <- function(f, starting_points, bounds){
  
  #Check input
  assert_that(is.function(f))
  assert_that(is.numeric(starting_points))
  assert_that(length(bounds) == 2, is.numeric(bounds))
  assert_that(bounds[1] < bounds[2])
  
  
  # get function for calculating derivative at a certain point
  f_deriv <- function(x) {
    return(grad(f, x))
  }
  
  # sort T to be in order
  T_values <- init_T(starting_points)
  
  # evaluate f and its derivative at the starting values
  calculated_f <- sapply(T_values, f)
  calculated_f_deriv <- sapply(T_values, f_deriv)
  
  # find intersection points
  Z_values <- find_Z(calculated_f, calculated_f_deriv, T_values)
  
  # evaluate U,L,S at starting values
  U_values <- sapply(T_values, find_U, calculated_f, calculated_f_deriv, Z_values, T_values, bounds)
  L_values <- sapply(T_values, find_L, calculated_f, T_values, bounds)  
  # ADD S!!
  
  #Check outputs 
  
  assert_that(is.numeric(Z_values), is.numeric(U_values), is.numeric(L_values),
              is.numeric(T_values), is.numeric(bounds), 
              is.numeric(calculated_f_deriv), is.numeric(calculated_f))
  assert_that( min(c(length(T_values), length(U_values), 
                     length(L_values), length(calculated_f_deriv), 
                     length(calculated_f))) ==
                 max(c(length(T_values), length(U_values), 
                       length(L_values), length(calculated_f_deriv), 
                       length(calculated_f))))
  assert_that(length(Z_values) == (length(T_values)-1))
  
  return(list("f_deriv" = f_deriv, 
              "T_values" = T_values, 
              "calculated_f" = calculated_f,
              "calculated_f_deriv" = calculated_f_deriv,
              "Z_values" = Z_values,
              "U_values" = U_values,
              "L_values" = L_values))
  
}



update_step <- function(x_star, T_values, f, f_deriv, bounds, k){
  # A function that performs the updating step. 
  # The function returns the new k value and T values.
  
  #Check inputs
  assert_that(is.function(f), is.function(f_deriv))
  assert_that(length(bounds) == 2)
  assert_that(bounds[1] < bounds[2])
  assert_that(is.numeric(x_star), is.numeric(T_values), is.numeric(k))
  assert_that(length(x_star) == 1, length(k) == 1, length(T_values) == k)
  
  #update T values
  
  T_values <- update_T(x_star, T_values, k)
  
  #construct:
  #uk+1, sk+1, lk+1
  
  calced_functions <- calc_functions(T_values, T_values, f, f_deriv, bounds)
  
  Z_values <- calced_functions$Z_values
  U_values <- calced_functions$U_values
  L_values <- calced_functions$L_values
  calculated_f <- calced_functions$calculated_f
  calculated_f_deriv <- calced_functions$calculated_f_deriv
  
  #increment k
  k <- k + 1 
  
  #Check outputs 
  assert_that(is.numeric(k), length(k) == 1)
  
  return(list("Z_values" = Z_values,
              "U_values" = U_values,
              "L_values" = L_values,
              "k" = k,
              "T_values" = T_values,
              "calculated_f" = calculated_f,
              "calculated_f_deriv" = calculated_f_deriv
  ))
  
}

update_T <- function(x_star, T_values , k){
  #A function that adds the accepted sample to
  # the T values and sorts the T values. 
  # The function returns the updated T_k+1 values. 
  
  #checking inputs 
  assert_that(is.numeric(x_star), length(x_star) == 1)
  assert_that(is.numeric(k), length(k) == 1)
  assert_that(is.numeric(T_values), length(T_values) == k)
  
  #add x* to Tk
  T_values[k+1] <- x_star
  
  #relabel elements of Tk+1 in ascending order
  T_values <- sort(T_values)
  
  #check output
  assert_that(is.numeric(T_values), length(T_values) == (k+1))
  
  return(T_values)
  
}



sampling_step <- function(T_values, f, f_deriv, bounds, Z_values, 
                          U_values, calculated_f_deriv, calculated_f){
  #A function that performs the sampling step by sampling
  # and then performs the squeezing test and rejection
  # test if relevant. The function returns the sample,
  # whether the sample was accepted and 
  # whether h, h' were evaluated. 

  #Check inputs
  assert_that(is.numeric(Z_values), is.numeric(U_values), 
              is.numeric(T_values), is.numeric(bounds), 
              is.numeric(calculated_f_deriv), is.numeric(calculated_f))
  assert_that(is.function(f), is.function(f_deriv))
  assert_that( min(c(length(T_values), length(U_values), 
                 length(calculated_f_deriv), length(calculated_f))) ==
                 max(c(length(T_values), length(U_values), 
                 length(calculated_f_deriv), length(calculated_f))))
  assert_that(length(Z_values) == (length(T_values)-1))
  assert_that(length(bounds) == 2)
  assert_that(bounds[1] < bounds[2])
  
  #Sample from s_k equation
  x_star <- sample_s(bounds[1], bounds[2], Z_values, U_values, T_values, 
                     calculated_f_deriv, calculated_f)
  
  #Sample from UNIF[0,1]
  w <- runif(1)
  
  #Evaluate the equations for T_k and the sampled value
  
  calced_functions <- calc_functions(x_star, T_values, f, f_deriv, bounds)
  
  U_star <- calced_functions$U_values
  L_star <- calced_functions$L_values
  h_star <- f(x_star)
  
  #Perform squeezing test
  
  squeezing_tested <- squeezing_test(w, U_star, L_star)
  h_eval <- squeezing_tested$h_eval
  accepted <- squeezing_tested$accepted
  
  if(accepted == FALSE){
    #if squeezing test not passed then do rejection_test
    
    accepted <- rejection_test(w, x_star, U_star)

  }
  
  #Check output
  assert_that(is.logical(accepted), length(accepted) == 1)
  assert_that(is.logical(h_eval), length(h_eval) == 1)
  assert_that(is.numeric(x_star), length(x_star) == 1)
  
  return(list("h_eval" = h_eval,
              "accepted" = accepted,
              "x_star" = x_star))
  
}

squeezing_test <- function(w, U_star, L_star){
  #A function that performs the squeezing test
  #for a given w, value of u_k equation for the sample
  #and given value of l_k equation for the sample
  
  #Check input 
  assert_that(is.numeric(w), is.numeric(U_star), is.numeric(L_star))
  assert_that(length(w) == 1, length(U_star) == 1, length(L_star) == 1)
  #assert_that(U_star >= L_star, U_star >= 0, L_star >= 0)
  assert_that(w >= 0, w <= 1)
  
  tol <- exp(L_star - U_star)
  
  #check if test is passed
  if( w <= tol ){
    #if test if passed then sample accepted and h not evaluated  
    
    accepted <- TRUE
    h_eval <- FALSE
    
  } else {
    #if test if not passed then sample not accepted and h will be evaluated 
    
    accepted <- FALSE
    h_eval <- TRUE
    
  }
  
  #Check output
  assert_that(is.logical(accepted), length(accepted) == 1)
  assert_that(is.logical(h_eval), length(h_eval) == 1)
  
  return(list("accepted" = accepted,
              "h_eval" = h_eval))
  
}

rejection_test <- function(w, h_star, U_star){
  #A function that performs the rejection test
  #for a given w, value of h for the sample
  #and given value of u_k equation for the sample
  
  #Check input 
  assert_that(is.numeric(w), is.numeric(h_star), is.numeric(U_star))
  assert_that(length(w) == 1, length(h_star) == 1, length(U_star) == 1)
  #assert_that(U_star >= h_star, U_star >= 0)
  assert_that(w >= 0, w <= 1)
  
  tol <- exp(h_star - U_star)
  
  if(w <= tol){
    #if test is passed then accept sample 
    
    accepted <- TRUE
    
  }else{
    #otherwise don't accept sample
    
    accepted <- FALSE
    
  }
  
  #check output
  assert_that(is.logical(accepted), length(accepted) == 1)
  
  return(accepted)
  
}

calc_functions <- function(x, T_values, f, f_deriv, bounds){
  #A function that evaluates Z and equations for u_k, l_k and s_k
  #for given T_k values and returns the corresponding values of the
  #equations for given x values. 
  
  #Check inputs
  assert_that(is.numeric(x), is.numeric(T_values), is.numeric(bounds))
  assert_that(is.function(f), is.function(f_deriv))
  assert_that(length(x) <= length(T_values), length(bounds) == 2)
  assert_that(bounds[1] < bounds[2])
  
  # evaluate f and its derivative at the starting values
  calculated_f <- sapply(T_values, f)
  calculated_f_deriv <- sapply(T_values, f_deriv)
  
  # find intersection points
  Z_values <- find_Z(calculated_f, calculated_f_deriv, T_values)
  
  # evaluate U,L,S at starting values
  U_values <- sapply(x, find_U, calculated_f, calculated_f_deriv, Z_values, T_values, bounds)
  L_values <- sapply(x, find_L, calculated_f, T_values, bounds)  
  # ADD S!!
  
  #Check output
  assert_that(is.numeric(Z_values), is.numeric(U_values), is.numeric(L_values),
              is.numeric(calculated_f), is.numeric(calculated_f_deriv))
  #assert_that(length(U_values) == length(x), 
             # length(L_values) == length(x), length(calculated_f) == length(x), 
              #length(calculated_f_deriv) == length(x))
  #assert_that(all(U_values >= 0), all(L_values >= 0), all(Z_values >= 0))
  assert_that(all(!is.na(U_values)), all(!is.na(L_values)), 
              all(!is.na(Z_values)))
  
  return(list("Z_values" = Z_values,
              "U_values" = U_values,
              "L_values" = L_values,
              "calculated_f" = calculated_f,
              "calculated_f_deriv" = calculated_f_deriv))
  
}

```


```{r}
main(dnorm, n=100)
```





